In [2]:
import numpy as np

In [4]:
x=np.array([1,2,3])

In [5]:
x

array([1, 2, 3])

In [6]:
y=np.array([2,3.9,6.1])

In [7]:
y

array([2. , 3.9, 6.1])

##  中心化

In [8]:
x.mean()

2.0

In [9]:
y.mean()

4.0

In [10]:
xc = x -x.mean()

In [11]:
xc

array([-1.,  0.,  1.])

In [12]:
yc = y -y.mean()

In [13]:
yc

array([-2. , -0.1,  2.1])

## パラメータaの計算

In [16]:
xx = xc*xc

In [17]:
xx

array([1., 0., 1.])

In [19]:
xy = xc*yc

In [20]:
xx.sum()

2.0

In [21]:
xy.sum()

4.1

In [22]:
a = xy.sum()/xx.sum()

In [23]:
a

2.05